/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    ConnectionStatus: typeof import('./src/components/ConnectionStatus.vue')['default']
    EntityListPanel: typeof import('./src/components/panels/EntityListPanel.vue')['default']
    GameStatePanel: typeof import('./src/components/panels/GameStatePanel.vue')['default']
    ModeSwitcherFloatingMenu: typeof import('./src/components/ModeSwitcherFloatingMenu.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/panels/SettingsPanel.vue')['default']
  }
}
