//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAESandBox.Workflow.AIService.AiConfig.Doubao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DoubaoConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoubaoConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAESandBox.Workflow.AIService.AiConfig.Doubao.DoubaoConfigResources", typeof(DoubaoConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问豆包AI服务所需的API密钥。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ApiKey_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API密钥.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ApiKey_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ApiKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的豆包API密钥.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ApiKey_Prompt {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ApiKey_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据Token在文本中已出现的频率来惩罚新Token，从而减少逐字重复。正值会降低重复性。取值范围通常在 -2.0 到 2.0 之间。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_FrequencyPenalty_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_FrequencyPenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频率惩罚 (Frequency Penalty).
        /// </summary>
        public static string DoubaoAiProcessorConfig_FrequencyPenalty_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_FrequencyPenalty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整指定 token 在模型输出内容中出现的概率，使模型生成的内容更加符合特定的偏好。logit_bias 字段接受一个 map 值，其中每个键为词表中的 token ID（使用 tokenization 接口获取），每个值为该 token 的偏差值，取值范围为 [-100, 100]。
        ///-1 会减少选择的可能性，1 会增加选择的可能性；-100 会完全禁止选择该 token，100 会导致仅可选择该 token。该参数的实际效果可能因模型而异。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_LogitBias_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_LogitBias_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logit偏置 (Logit Bias).
        /// </summary>
        public static string DoubaoAiProcessorConfig_LogitBias_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_LogitBias_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否返回输出 tokens 的对数概率。
        ///false：不返回对数概率信息。
        ///true：返回消息内容中每个输出 token 的对数概率。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_Logprobs_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_Logprobs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回Logprobs.
        /// </summary>
        public static string DoubaoAiProcessorConfig_Logprobs_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_Logprobs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要使用的豆包AI模型名称，例如 &apos;doubao-pro-32k&apos; 或 &apos;doubao-lite-128k&apos;。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ModelName_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ModelName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型名称.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ModelName_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ModelName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据Token是否已在文本中出现至少一次来惩罚新Token，从而鼓励模型引入新的概念和主题。取值范围通常在 -2.0 到 2.0 之间。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_PresencePenalty_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_PresencePenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在惩罚 (Presence Penalty).
        /// </summary>
        public static string DoubaoAiProcessorConfig_PresencePenalty_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_PresencePenalty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定模型响应的格式。可选值为 &quot;text&quot;（默认）或 &quot;json_object&quot;（强制模型输出有效的JSON对象）。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ResponseFormatType_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ResponseFormatType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应格式类型.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ResponseFormatType_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ResponseFormatType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定是否使用TPM保障包。生效对象为购买了保障包推理接入点。取值范围：
        ///auto：优先使用TPM保障包。如果有TPM保障包额度的推理接入点，本次请求将会使用 TPM 保障包用量，获得更高限流以及响应速度。否则不使用，使用默认的限流和普通的服务响应速度。
        ///default：本次请求，不使用 TPM 保障包，使用默认的限流和普通的服务响应速度，即使请求的是有TPM保障包额度的推理接入点。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ServiceTier_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ServiceTier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务等级.
        /// </summary>
        public static string DoubaoAiProcessorConfig_ServiceTier_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_ServiceTier_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型遇到该字段所指定的字符串时将停止继续生成，这个词语本身不会输出。最多支持 4 个字符串。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_StopSequences_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_StopSequences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止序列 (Stop Sequences).
        /// </summary>
        public static string DoubaoAiProcessorConfig_StopSequences_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_StopSequences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式调用时，默认不统计 token 用量信息，返回值为null。
        ///如需统计，需设置 stream_options.include_usage为true。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_StreamOptions_IncludeUsage_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_StreamOptions_IncludeUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式响应选项——token用量.
        /// </summary>
        public static string DoubaoAiProcessorConfig_StreamOptions_IncludeUsage_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_StreamOptions_IncludeUsage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制生成文本的随机性。较低的值（如0.2）使输出更具确定性和重点，较高的值（如0.8）使其更随机。默认值通常为0.7或0.9，具体取决于模型。取值范围一般为 0.0 到 2.0。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_Temperature_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 温度 (Temperature).
        /// </summary>
        public static string DoubaoAiProcessorConfig_Temperature_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_Temperature_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取值范围为 [0, 20]。
        ///指定每个输出 token 位置最有可能返回的 token 数量，每个 token 都有关联的对数概率。仅当 logprobs为true 时可以设置 top_logprobs 参数。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_TopLogprobs_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_TopLogprobs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Logprobs数量.
        /// </summary>
        public static string DoubaoAiProcessorConfig_TopLogprobs_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_TopLogprobs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核采样概率阈值。模型会考虑概率质量在 top_p 内的 token 结果。当取值为 0 时模型仅考虑对数概率最大的一个 token。
        ///0.1 意味着只考虑概率质量最高的前 10% 的 token，取值越大生成的随机性越高，取值越低生成的确定性越高。通常建议仅调整 temperature 或 top_p 其中之一，不建议两者都修改。.
        /// </summary>
        public static string DoubaoAiProcessorConfig_TopP_Description {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_TopP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top P采样.
        /// </summary>
        public static string DoubaoAiProcessorConfig_TopP_Label {
            get {
                return ResourceManager.GetString("DoubaoAiProcessorConfig_TopP_Label", resourceCulture);
            }
        }
    }
}
