//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace YAESandBox.Workflow.AIService.AiConfig.Doubao {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class DoubaoAiResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoubaoAiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("YAESandBox.Workflow.AIService.AiConfig.Doubao.DoubaoAiResources", typeof(DoubaoAiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定是否使用TPM保障包。生效对象为购买了保障包推理接入点。取值范围：
        ///auto：优先使用TPM保障包。如果有TPM保障包额度的推理接入点，本次请求将会使用 TPM 保障包用量，获得更高限流以及响应速度。否则不使用，使用默认的限流和普通的服务响应速度。
        ///default：本次请求，不使用 TPM 保障包，使用默认的限流和普通的服务响应速度，即使请求的是有TPM保障包额度的推理接入点。.
        /// </summary>
        public static string DoubaoAiConfig_ServiceTier_Description {
            get {
                return ResourceManager.GetString("DoubaoAiConfig_ServiceTier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务等级.
        /// </summary>
        public static string DoubaoAiConfig_ServiceTier_Label {
            get {
                return ResourceManager.GetString("DoubaoAiConfig_ServiceTier_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型遇到该字段所指定的字符串时将停止继续生成，这个词语本身不会输出。最多支持 4 个字符串。.
        /// </summary>
        public static string DoubaoAiConfig_StopSequences_Description {
            get {
                return ResourceManager.GetString("DoubaoAiConfig_StopSequences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止序列 (Stop Sequences).
        /// </summary>
        public static string DoubaoAiConfig_StopSequences_Label {
            get {
                return ResourceManager.GetString("DoubaoAiConfig_StopSequences_Label", resourceCulture);
            }
        }
    }
}
