//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAESandBox.Workflow.AIService.AiConfig.OpenAiCompatible {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OpenAiCompatibleAiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenAiCompatibleAiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAESandBox.Workflow.AIService.AiConfig.OpenAiCompatible.OpenAiCompatibleAiResourc" +
                            "es", typeof(OpenAiCompatibleAiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API 的基地址 (Base URL)。用于指定要连接的兼容 OpenAI 规范的 API 端点。例如: &quot;https://api.openai.com/v1/&quot; 或 &quot;https://your-custom-endpoint/v1/&quot;。.
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Description {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API 基地址 (Base URL).
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Label {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/.
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Prompt {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Prompt", resourceCulture);
            }
        }
    }
}
