//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace YAESandBox.Workflow.AIService.AiConfig.OpenAiCompatible {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class OpenAiCompatibleAiResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenAiCompatibleAiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("YAESandBox.Workflow.AIService.AiConfig.OpenAiCompatible.OpenAiCompatibleAiResourc" +
                                                               "es", typeof(OpenAiCompatibleAiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API 的基地址 (Base URL)。用于指定要连接的兼容 OpenAI 规范的 API 端点。例如: &quot;https://api.openai.com/v1/&quot; 或 &quot;https://your-custom-endpoint/v1/&quot;。.
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Description {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API 基地址 (Base URL).
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Label {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/.
        /// </summary>
        public static string OpenAiCompatible_BaseUrl_Prompt {
            get {
                return ResourceManager.GetString("OpenAiCompatible_BaseUrl_Prompt", resourceCulture);
            }
        }
    }
}
