//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAESandBox.Workflow.AIService.AiConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AiProcessorConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AiProcessorConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAESandBox.Workflow.AIService.AiConfig.AiProcessorConfigResources", typeof(AiProcessorConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为此AI服务配置指定一个易于识别的名称。建议确保其唯一性，以便管理。.
        /// </summary>
        public static string AbstractAiProcessorConfig_ConfigName_Description {
            get {
                return ResourceManager.GetString("AbstractAiProcessorConfig_ConfigName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置名称.
        /// </summary>
        public static string AbstractAiProcessorConfig_ConfigName_Label {
            get {
                return ResourceManager.GetString("AbstractAiProcessorConfig_ConfigName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI模型的内部类型标识符。此字段由系统根据具体配置类型自动设置，通常用于区分不同的AI服务实现，用户不应手动修改。.
        /// </summary>
        public static string AbstractAiProcessorConfig_ModuleType_Description {
            get {
                return ResourceManager.GetString("AbstractAiProcessorConfig_ModuleType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块类型.
        /// </summary>
        public static string AbstractAiProcessorConfig_ModuleType_Label {
            get {
                return ResourceManager.GetString("AbstractAiProcessorConfig_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值必须在 {0} 和 {1} 之间。.
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此字段为必填项。.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
