//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace YAESandBox.Workflow.AIService.AiConfig {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class GeneralAiResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralAiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("YAESandBox.Workflow.AIService.AiConfig.GeneralAiResources", typeof(GeneralAiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问AI服务所需的API密钥。.
        /// </summary>
        public static string GeneralAiConfig_ApiKey_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API密钥.
        /// </summary>
        public static string GeneralAiConfig_ApiKey_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ApiKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的AI API密钥.
        /// </summary>
        public static string GeneralAiConfig_ApiKey_Prompt {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ApiKey_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据Token在文本中已出现的频率来惩罚新Token，从而减少逐字重复。正值会降低重复性。取值范围通常在 -2.0 到 2.0 之间。.
        /// </summary>
        public static string GeneralAiConfig_FrequencyPenalty_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_FrequencyPenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频率惩罚 (Frequency Penalty).
        /// </summary>
        public static string GeneralAiConfig_FrequencyPenalty_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_FrequencyPenalty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整指定 token 在模型输出内容中出现的概率。logit_bias 接受一个 Token ID 到偏置值的映射，取值范围为 [-100, 100]。
        ///-1 会减少选择的可能性，1 会增加选择的可能性；-100 会完全禁止选择该 token，100 会导致仅可选择该 token。该参数的实际效果可能因模型而异。.
        /// </summary>
        public static string GeneralAiConfig_LogitBias_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_LogitBias_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logit偏置 (Logit Bias).
        /// </summary>
        public static string GeneralAiConfig_LogitBias_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_LogitBias_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否返回输出 tokens 的对数概率。
        ///false：不返回对数概率信息。
        ///true：返回消息内容中每个输出 token 的对数概率。.
        /// </summary>
        public static string GeneralAiConfig_Logprobs_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_Logprobs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回Logprobs.
        /// </summary>
        public static string GeneralAiConfig_Logprobs_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_Logprobs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置模型允许处理的最大输入Token数量。此设置主要用于在发送请求前进行内容截断或验证，通常不直接作为API参数发送。.
        /// </summary>
        public static string GeneralAiConfig_MaxInputTokens_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_MaxInputTokens_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大输入Token数.
        /// </summary>
        public static string GeneralAiConfig_MaxInputTokens_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_MaxInputTokens_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限制模型在单次响应中生成的最大Token数量。这可以用来控制响应的长度和成本。.
        /// </summary>
        public static string GeneralAiConfig_MaxOutputTokens_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_MaxOutputTokens_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大输出Token数.
        /// </summary>
        public static string GeneralAiConfig_MaxOutputTokens_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_MaxOutputTokens_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要使用的AI模型名称。.
        /// </summary>
        public static string GeneralAiConfig_ModelName_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ModelName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型名称.
        /// </summary>
        public static string GeneralAiConfig_ModelName_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ModelName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据Token是否已在文本中出现至少一次来惩罚新Token，从而鼓励模型引入新的概念和主题。取值范围通常在 -2.0 到 2.0 之间。.
        /// </summary>
        public static string GeneralAiConfig_PresencePenalty_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_PresencePenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在惩罚 (Presence Penalty).
        /// </summary>
        public static string GeneralAiConfig_PresencePenalty_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_PresencePenalty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定模型响应的格式。可选值为 &quot;text&quot;（默认）或 &quot;json_object&quot;（强制模型输出有效的JSON对象）。.
        /// </summary>
        public static string GeneralAiConfig_ResponseFormatType_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ResponseFormatType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应格式类型.
        /// </summary>
        public static string GeneralAiConfig_ResponseFormatType_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ResponseFormatType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定请求的服务等级。.
        /// </summary>
        public static string GeneralAiConfig_ServiceTier_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ServiceTier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务等级/优先级.
        /// </summary>
        public static string GeneralAiConfig_ServiceTier_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_ServiceTier_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型遇到该字段所指定的字符串时将停止继续生成。.
        /// </summary>
        public static string GeneralAiConfig_StopSequences_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_StopSequences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止序列 (Stop Sequences).
        /// </summary>
        public static string GeneralAiConfig_StopSequences_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_StopSequences_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式调用时，是否在响应结束时返回 token 用量信息。设置为true会包含这些统计数据。.
        /// </summary>
        public static string GeneralAiConfig_StreamOptions_IncludeUsage_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_StreamOptions_IncludeUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式响应选项——包含用量统计.
        /// </summary>
        public static string GeneralAiConfig_StreamOptions_IncludeUsage_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_StreamOptions_IncludeUsage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制生成文本的随机性。较低的值（如0.2）使输出更具确定性和重点，较高的值（如0.8）使其更随机。默认值通常为0.7或0.9，具体取决于模型。取值范围一般为 0.0 到 2.0。.
        /// </summary>
        public static string GeneralAiConfig_Temperature_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 温度 (Temperature).
        /// </summary>
        public static string GeneralAiConfig_Temperature_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_Temperature_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过从 K 个最可能的下一个词元（token）中进行采样来控制生成内容的多样性。较高的值意味着更多样化，较低的值会使输出更集中和确定。.
        /// </summary>
        public static string GeneralAiConfig_TopK_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopK_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-K.
        /// </summary>
        public static string GeneralAiConfig_TopK_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopK_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取值范围为 [0, 20]。
        ///指定每个输出 token 位置最有可能返回的 token 数量，每个 token 都有关联的对数概率。仅当 Logprobs为true 时此参数生效。.
        /// </summary>
        public static string GeneralAiConfig_TopLogprobs_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopLogprobs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Logprobs数量.
        /// </summary>
        public static string GeneralAiConfig_TopLogprobs_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopLogprobs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核心采样参数，模型会考虑概率总和为 top_p 的token。通常建议仅调整 temperature 或 top_p 其中之一，不建议两者都修改。.
        /// </summary>
        public static string GeneralAiConfig_TopP_Description {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top P采样.
        /// </summary>
        public static string GeneralAiConfig_TopP_Label {
            get {
                return ResourceManager.GetString("GeneralAiConfig_TopP_Label", resourceCulture);
            }
        }
    }
}
