// 统一图标库
export {default as GameControllerIcon} from '@vicons/ionicons5/es/GameControllerOutline';
export {default as CloseIcon} from '@vicons/ionicons5/es/CloseOutline';
export {default as InfoIcon} from '@vicons/ionicons5/es/InformationCircleOutline';
export {default as AddBoxIcon} from '@vicons/material/es/AddBoxOutlined';
export {default as SwapHorizIcon} from '@vicons/material/es/SwapHorizOutlined';
export {default as PeopleIcon} from '@vicons/ionicons5/es/PeopleOutline';
export {default as EditIcon} from '@vicons/material/es/EditOutlined';
export {default as LinkOffIcon} from '@vicons/material/es/LinkOffOutlined';
export {default as FindInPageIcon} from '@vicons/material/es/FindInPageOutlined';
export {default as SaveIcon} from '@vicons/material/es/SaveOutlined';
export {default as KeyboardArrowDownIcon} from '@vicons/material/es/KeyboardArrowDownFilled';
export {default as KeyboardArrowUpIcon} from '@vicons/material/es/KeyboardArrowUpFilled';
export {default as ArrowForwardIcon} from '@vicons/material/es/ArrowForwardOutlined';
export {default as DeleteIcon} from '@vicons/material/es/DeleteOutlineRound';
export {default as SettingsIcon} from '@vicons/ionicons5/es/SettingsOutline';
export {default as DragHandleIcon} from '@vicons/material/es/DragHandleOutlined';
export {default as AddIcon} from '@vicons/material/es/AddCircleOutlineRound';
export {default as ListIcon} from '@vicons/ionicons5/es/ListOutline';
export {default as HelpCircleIcon} from '@vicons/ionicons5/es/HelpCircleOutline';
export {default as AlertCircleIcon} from '@vicons/ionicons5/es/AlertCircleOutline';
export {default as WorkflowIcon} from '@vicons/material/es/AccountTreeOutlined';
export {default as TuumIcon} from '@vicons/material/es/AccountTreeOutlined';
export {default as TrashIcon} from '@vicons/ionicons5/es/TrashBinOutline';
export {default as EllipsisHorizontalIcon} from '@vicons/ionicons5/es/EllipsisHorizontal';
export {default as ChevronDownIcon} from '@vicons/ionicons5/es/ChevronDownOutline';
export {default as PricetagIcon} from '@vicons/ionicons5/es/PricetagOutline';
export {default as LinkIcon} from '@vicons/ionicons5/es/LinkOutline';
export {default as DocumentTextIcon} from '@vicons/ionicons5/es/DocumentTextOutline';
export {default as CloudUploadIcon} from '@vicons/ionicons5/es/CloudUploadOutline';
export {default as CloudDownloadIcon } from '@vicons/ionicons5/es/CloudDownloadOutline';
export {default as ChevronLeftIcon}from'@vicons/material/es/ChevronLeftOutlined';
export {default as ChevronRightIcon}from'@vicons/material/es/ChevronRightOutlined';
export {default as RefreshIcon}from'@vicons/ionicons5/es/Refresh';
export {default as CodeIcon}from'@vicons/ionicons5/es/CodeSlashOutline';
export {default as FullscreenExitIcon}from'@vicons/material/es/FullscreenExitOutlined';
export {default as FullscreenIcon}from'@vicons/material/es/FullscreenOutlined';
export {default as LoginIcon}from'@vicons/ionicons5/es/LogInOutline';
export {default as HubIcon}from'@vicons/material/es/HubOutlined';
export {default as GraphIcon}from'@vicons/material/es/AutoGraphOutlined';
export {default as SparklesIcon}from'@vicons/ionicons5/es/SparklesOutline';
export {default as ErrorIcon}from'@vicons/material/es/ErrorOutlined';
export {default as WarningIcon}from'@vicons/material/es/WarningOutlined';
export {default as FolderIcon}from'@vicons/ionicons5/es/FolderOutline';
export {default as PlayIcon}from'@vicons/ionicons5/es/PlayCircleOutline';
export {default as PauseIcon}from'@vicons/ionicons5/es/PauseCircleOutline';
export {default as CopyIcon}from'@vicons/ionicons5/es/CopyOutline';
// export {default as }from'@vicons/ionicons5/es/';